### ISSUE TITLE
Only appearing once on RaspPi

### ISSUE THREAD

**Issue by UsernameExpired** [mrdis/MMM-google-route#8] opened 2018-12-12 19:19 UTC
When running the module on a raspberry pi installation of MagicMirror2 the module is only able to load once within a configuration, when multiple modules of the same configuration are entered still only one loads however on a docker installation of MagicMirror2 running the same configuration file both modules successfully appear.

**Comment by mrdis** [comment] 2018-12-14 18:31
I don't have a raspberry around, so I'm not able to reproduce the issue. Could you check the developer tools console in electron and see if any errors appear there? I can't figure out the reason for such a behavior.

**Comment by mrdis** [comment] 2018-12-23 16:44
Please update to the latest version, it should show if any error occurs during the refreshing of the routes.

**Comment by mrdis** [comment] 2019-01-09 17:24
I'm closing this since there are no further comments from almost a month.

**Closed by mrdis** 2019-01-09 17:24 UTC
